# Generated by Django 6.1.1 on 2026-09-16 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=100)),
                ('room_type', models.CharField(choices=[('suite', 'Suite'), ('standart', 'Standar Room'), ('deluxe', 'Deluxe Room')], max_length=100)),
                ('pricePerNight', models.IntegerField(default=150)),
                ('currency', models.CharField(choices=[('USD', 'USD'), ('COP', 'COP')], default='USD', max_length=10)),
                ('maxOccupancy', models.IntegerField(default=1)),
                ('description', models.TextField(max_length=1000)),
            ],
        ),
    ]
